-- Databricks notebook source
-- Portfolio/Demo Version - Generic catalog and schema names
CREATE TABLE demo_catalog.change_management_tbl.servicenow_change_request (
  additional_assignee_list STRING,
  app_ci STRING,
  application_location STRING,
  application_service_name_key STRING,
  assigned_to STRING,
  assignment_group STRING,
  change_advisory_board_approval_date TIMESTAMP,
  change_advisory_board_authorizer STRING,
  change_advisory_board_delegate STRING,
  change_advisory_board_recommendation STRING,
  closing_comment_and_work_note STRING,
  configuration_item_type STRING,
  conflict_last_run_dtml TIMESTAMP,
  conflict_status STRING,
  current_request_state STRING,
  emergency_request_justification STRING,
  end_user_impact STRING,
  impacted_service STRING,
  incident_number STRING,
  is_change_advisory_board_decision_required BOOLEAN,
  is_conflict_warning_accepted BOOLEAN,
  is_knowledge_article_found BOOLEAN,
  is_pre_release_test_required BOOLEAN,
  is_request_active BOOLEAN,
  is_request_for_production_environment BOOLEAN,
  is_request_post_implementation_review_required BOOLEAN,
  is_request_unauthorized BOOLEAN,
  is_sla_met BOOLEAN,
  is_there_a_failover_plan BOOLEAN,
  knowledge_of_other_impacted_app_ci STRING,
  outage_summary STRING,
  parent_task STRING,
  planned_outage_type STRING,
  plan_plus_project_name STRING,
  pre_release_test_plan STRING,
  pre_release_test_result STRING,
  problem_number STRING,
  record_created_by STRING,
  record_create_dtml TIMESTAMP,
  request_approval_dtml TIMESTAMP,
  request_approval_history STRING,
  request_approval_status STRING,
  request_backout_plan STRING,
  request_category STRING,
  request_closed_by STRING,
  request_closed_dtml TIMESTAMP,
  request_comment STRING,
  request_conflict_status STRING,
  request_description STRING,
  request_duration DECIMAL(10,2),
  requested_by STRING,
  request_emergency_deployment_justification STRING,
  request_end_dtml TIMESTAMP,
  request_execution_method STRING,
  request_fallback_duration DECIMAL(10,2),
  request_impact STRING,
  request_impact_category STRING,
  request_impact_description STRING,
  request_impacted_location STRING,
  request_implementation_group STRING,
  request_implementation_plan STRING,
  request_implementation_result STRING,
  request_implementation_timeline STRING,
  request_justification STRING,
  request_number STRING,
  request_opened_by STRING,
  request_opened_dtml TIMESTAMP,
  request_post_implementation_review_date TIMESTAMP,
  request_post_implementation_review_owner STRING,
  request_post_implementation_review_reason STRING,
  request_post_implementation_review_result STRING,
  request_priority INT,
  request_resolution_category STRING,
  request_resolution_notes STRING,
  request_review_comment STRING,
  request_risk_category STRING,
  request_risk_impact STRING,
  request_risk_value STRING,
  request_short_description STRING,
  request_source STRING,
  request_start_dtml TIMESTAMP,
  request_type STRING,
  request_validation_plan STRING,
  request_work_end_dtml TIMESTAMP,
  request_work_start_dtml TIMESTAMP,
  standard_change_template_name STRING,
  standard_change_template_version STRING,
  system_record_id STRING,
  system_record_tag_list STRING,
  task_work_notes STRING,
  third_party_company STRING,
  ucloud_ingestion_date DATE,
  watch_list STRING,
  feed_id INT,
  feed_version INT,
  ingestion_id BIGINT,
  ingestion_timestamp TIMESTAMP
)
USING delta
LOCATION 's3://demo-lakehouse-bucket/change_management/servicenow_change_request'
COMMENT 'ServiceNow change request data. Portfolio demo project - example implementation.'
TBLPROPERTIES (
  'delta.checkpoint.writeStatsAsJson' = 'false',
  'delta.checkpoint.writeStatsAsStruct' = 'true',
  'delta.checkpointPolicy' = 'v2',
  'delta.columnMapping.mode' = 'name',
  'delta.deletedFileRetentionDuration' = 'interval 24 hours',
  'delta.enableChangeDataFeed' = 'true',
  'delta.enableDeletionVectors' = 'false',
  'delta.enableIcebergCompatV2' = 'true',
  'delta.feature.appendOnly' = 'supported',
  'delta.feature.changeDataFeed' = 'supported',
  'delta.feature.columnMapping' = 'supported',
  'delta.feature.deletionVectors' = 'supported',
  'delta.feature.icebergCompatV2' = 'supported',
  'delta.feature.invariants' = 'supported',
  'delta.feature.v2Checkpoint' = 'supported',
  'delta.universalFormat.enabledFormats' = 'iceberg')
  ;

